export const metadata = {
    title: 'Profile',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <div className='relative flex h-screen w-screen items-end justify-center'>{children}</div>;
}
