'use client';

import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Provider } from 'react-redux';
import { SessionProvider } from 'next-auth/react';
import store from './redux/store';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Quizzes',
    description: 'Generated by create next app',
    icons: '/assets/images/logoApp.png'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <head>
                <title>Quizzes</title>
                <link rel='shortcut icon' href='/assets/images/logoApp.png' />
            </head>
            <body className={inter.className + ' bg-gray-100 dark:bg-slate-600 '}>
                <Provider store={store}>
                    <SessionProvider>{children}</SessionProvider>
                </Provider>
            </body>
        </html>
    );
}
