export const metadata = {
    title: 'Auth',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className='relative flex h-screen w-screen items-center justify-center'>
            {children}
        </div>
    );
}
