// export const metadata = {
//   title: "Auth",
//   description: "Generated by create next app",
// };

import WithAuth from 'src/components/common/WithAuth';

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return <div className='flex min-h-screen'>{children}</div>;
}
